### ISSUE TITLE
project setup

### ISSUE THREAD

**Issue by pmarx92** [pmarx92/capstone-prep#1]
## Value statement - a requirement, not a solution
As a user 
I need a navbar
so that i can navigate around

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/74617403/197206611-44122ea3-973d-4409-a6bd-03c7b9e6a244.png)

## Acceptance criteria
- [ ] the App should have a Header
- [ ] the App should have a navbar
- [ ] 4 possible pages / links inside the navbar

## Tasks
- [ ] add the Header
- [ ] create the navbar
- [ ] add all empty pages

## Size
small

**Comment by edanum** [comment]
als task fehlt eventuell noch das linken der navelemente mit den pages :) Und wie siehts mit einer "acitve" anzeige für das zugehörige Navelement aus, damit man weiß wo man ist?

**Comment by pmarx92** [comment]
> als task fehlt eventuell noch das linken der navelemente mit den pages :) Und wie siehts mit einer "acitve" anzeige für das zugehörige Navelement aus, damit man weiß wo man ist?

Das verlinken war von mir gemeint mit "links inside the navbar", ich verbesser das mal :) eine active anzeige ist ne gute idee, bau ich auch noch mit ein!

**Comment by mpagels** [comment]
Good user story as a second or third one. Just saying. It is the first user story from you I'm reading. If so: Very good work here. Keep up!

**Comment by Kheirah** [comment]
> > Good user story as a second or third one. Just saying. It is the first user story from you I'm reading. If so: Very good work here. Keep up!
> 
> Thanks :) But what do you mean with "second or third one"? I mean i need to start somewhere. Or did i miss something?

I think Martin wants to say that a navigation bar on its own is of rather little value to the user since they navigate to a blank screen wherever they go. A different start could be to show some dummy data on the home page and then add other pages. Once the pages themselves are added you can create the navigation between them.

There's no right or wrong. If you choose to start with a navigation bar, go ahead 😄
