### ISSUE TITLE
userStory #2

### ISSUE THREAD

**Issue by pmarx92** [pmarx92/capstone-prep#2]
## Value statement - a requirement, not a solution
As a user
I need a form
so that i can add all my information about that fishing spot

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/74617403/197548805-5eae240f-9a79-40a3-9604-d46e034a88a8.png)

## Acceptance criteria
- [ ] i need a form with different inputs inside the "Add Location" page
- [ ] the information should be stored

## Tasks
- [ ] add the form inside the "Add Location" page
- [ ] add 5 inputfields, time and date, name, weight, length, location
- [ ] add a submit button
- [ ] add localStorage so that the information is save after each refresh

## Size
medium
