### ISSUE TITLE
userStory 

### ISSUE THREAD

**Issue by pmarx92** [pmarx92/capstone-prep#4]
## Value statement - a requirement, not a solution
As a user
I want to be able to edit and delete those new added cards
so that i can clean up the list

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/74617403/197558622-25d2e85b-62f8-42d9-8f50-70ba58cf00ae.png)

## Acceptance criteria
- [ ] i want to edit the cards
- [ ] i want to delete the cards

## Tasks
- [ ] add a delete button to the card
- [ ] add a edit button to the card

## Size
medium

**Comment by VladF146** [comment]
Do you just want to add the Buttons or the functionality as well?

**Comment by pmarx92** [comment]
> Do you just want to add the Buttons or the functionality as well?

I want the functionality as well. Maybe i should mention that, thanks :)
